AWSTemplateFormatVersion: '2010-09-09'
Description: Auctions table

Resources:
  AuctionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Auctions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: item_name
          AttributeType: S
        - AttributeName: end
          AttributeType: N
      KeySchema:
        - AttributeName: item_name
          KeyType: "HASH"
        - AttributeName: end
          KeyType: "RANGE"
